name: Bug Report (Git)
description: Neopilot Git-Related Bugs
type: "Bug"
labels: ["git"]
title: "Git: <a short description of the Git bug>"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the bug with a one line summary, and provide detailed reproduction steps
      value: |
        <!-- Please insert a one line summary of the issue below -->
        SUMMARY_SENTENCE_HERE

        ### Description
        <!--  Describe with sufficient detail to reproduce from a clean Neopilot install. -->
        Steps to trigger the problem:
        1.
        2.
        3.

        Actual Behavior:
        Expected Behavior:

    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Neopilot Version and System Specs
      description: 'Open Neopilot, and in the command palette select "neopilot: copy system specs into clipboard"'
      placeholder: |
        Output of "neopilot: copy system specs into clipboard"
    validations:
      required: true
