apiVersion: batch/v1
kind: Job
metadata:
  namespace: ${NEOPILOT_KUBE_NAMESPACE}
  name: ${NEOPILOT_MIGRATE_JOB_NAME}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          imagePullPolicy: Always
          image: ${NEOPILOT_IMAGE_ID}
          args:
            - migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
