[package]
name = "neopilot_ruff"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/ruff.rs"
crate-type = ["cdylib"]

[dependencies]
neopilot_extension_api = { path = "../../crates/extension_api" }
