[package]
name = "neopilot_proto"
version = "0.2.2"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/proto.rs"
crate-type = ["cdylib"]

[dependencies]
neopilot_extension_api = { path = "../../crates/extension_api" }
