id = "proto"
name = "Proto"
description = "Protocol Buffers support."
version = "0.2.2"
schema_version = 1
authors = ["Neopilot Industries <support@neopilot.dev>"]
repository = "https://github.com/khulnasoft-lab/neopilot"

[grammars.proto]
repository = "https://github.com/khulnasoft-lab/tree-sitter-proto"
commit = "0848bd30a64be48772e15fbb9d5ba8c0cc5772ad"

[language_servers.protobuf-language-server]
name = "Protobuf Language Server"
languages = ["Proto"]
